// token casa:
const token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IkVkdWFydGUgUGFpdmEiLCJlbWFpbCI6ImVkdWFydGUucG9AeWFob28uY29tLmJyIiwiYWRtaW4iOnRydWUsImlhdCI6MTY4Mjk0Mjg0OSwiZXhwIjoxNjgzMjAyMDQ5fQ.SsKYh5phM6DiLlnjRIBJ6BThNgmVD6Pk6pUdvljpr68'

//token trabalho: 
//const token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IkVkdWFydGUiLCJlbWFpbCI6ImVkdWFydGVAZ21haWwuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTY4MjQzMDkwOSwiZXhwIjoxNjgyNjkwMTA5fQ.NU4vaBHIs-0xhC0-avBmq1tlEpUgJ7saAaSQ5fX2rC8"


export default token