// token casa:
const token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IkVkdWFydGUgUGFpdmEgZGUgT2xpdmVpcmEiLCJlbWFpbCI6ImVkdWFydGUucG9AeWFob28uY29tLmJyIiwiYWRtaW4iOnRydWUsImlhdCI6MTY4MjY0NjU5MSwiZXhwIjoxNjgyOTA1NzkxfQ.XfY0htlB7mkPbKzFJve6o2J3oBpvAztIWKA1U95cIB8'

// token trabalho: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IkVkdWFydGUiLCJlbWFpbCI6ImVkdWFydGVAZ21haWwuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTY4MjQzMDkwOSwiZXhwIjoxNjgyNjkwMTA5fQ.NU4vaBHIs-0xhC0-avBmq1tlEpUgJ7saAaSQ5fX2rC8
//const token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IkVkdWFydGUiLCJlbWFpbCI6ImVkdWFydGVAZ21haWwuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTY4MjQzMDkwOSwiZXhwIjoxNjgyNjkwMTA5fQ.NU4vaBHIs-0xhC0-avBmq1tlEpUgJ7saAaSQ5fX2rC8"


export default token